-- =============================================================
-- Demo seed: customers & orders (static data)
-- 30 customers, 54 orders (0–4 per customer)
-- =============================================================

BEGIN;

DROP TABLE IF EXISTS orders;
DROP TABLE IF EXISTS customers;

CREATE TABLE customers (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name  VARCHAR(100) NOT NULL,
    last_name   VARCHAR(100) NOT NULL,
    email       VARCHAR(255) NOT NULL UNIQUE,
    city        VARCHAR(100),
    country     CHAR(2)      NOT NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE orders (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id   INTEGER       NOT NULL REFERENCES customers(id) ON DELETE CASCADE,
    order_number  VARCHAR(20)   NOT NULL UNIQUE,
    order_date    TIMESTAMPTZ   NOT NULL,
    status        VARCHAR(20)   NOT NULL
                  CHECK (status IN ('pending','paid','shipped','delivered','cancelled','refunded')),
    total_amount  NUMERIC(10,2) NOT NULL CHECK (total_amount >= 0),
    currency      CHAR(3)       NOT NULL
);

CREATE INDEX idx_orders_customer_id ON orders(customer_id);
CREATE INDEX idx_orders_order_date  ON orders(order_date);

-- -------------------------------------------------------------
-- Customers
-- -------------------------------------------------------------
INSERT INTO customers (id, first_name, last_name, email, city, country, created_at) VALUES
( 1, 'Olivia',   'Bennett',   'olivia.bennett@example.com',   'London',     'GB', '2024-01-08 09:14:00+00'),
( 2, 'Marcus',   'Hale',      'marcus.hale@example.net',      'Manchester', 'GB', '2024-01-15 17:42:00+00'),
( 3, 'Priya',    'Raman',     'priya.raman@example.org',      'Birmingham', 'GB', '2024-01-22 12:05:00+00'),
( 4, 'Daniel',   'Okafor',    'd.okafor@example.com',         'Leeds',      'GB', '2024-02-03 08:31:00+00'),
( 5, 'Sophie',   'Laurent',   'sophie.laurent@example.com',   'Paris',      'FR', '2024-02-11 19:20:00+00'),
( 6, 'Tomás',    'Rivera',    'tomas.rivera@example.com',     'Madrid',     'ES', '2024-02-19 14:47:00+00'),
( 7, 'Hannah',   'Fischer',   'hannah.fischer@example.org',   'Berlin',     'DE', '2024-03-02 10:10:00+00'),
( 8, 'James',    'Whitaker',  'jwhitaker@example.com',        'Bristol',    'GB', '2024-03-10 21:03:00+00'),
( 9, 'Aisha',    'Mensah',    'aisha.mensah@example.net',     'Dublin',     'IE', '2024-03-18 11:36:00+00'),
(10, 'Liam',     'O''Connor', 'liam.oconnor@example.com',     'Cork',       'IE', '2024-04-01 16:22:00+00'),
(11, 'Emma',     'Johansson', 'emma.johansson@example.org',   'Stockholm',  'SE', '2024-04-09 07:58:00+00'),
(12, 'Noah',     'Kim',       'noah.kim@example.com',         'Toronto',    'CA', '2024-04-20 15:44:00+00'),
(13, 'Chloe',    'Martin',    'chloe.martin@example.net',     'Lyon',       'FR', '2024-05-05 13:17:00+00'),
(14, 'Ethan',    'Brooks',    'ethan.brooks@example.com',     'New York',   'US', '2024-05-14 22:09:00+00'),
(15, 'Isabella', 'Rossi',     'isabella.rossi@example.org',   'Milan',      'IT', '2024-05-27 09:51:00+00'),
(16, 'Oliver',   'Grant',     'oliver.grant@example.com',     'Edinburgh',  'GB', '2024-06-03 18:26:00+00'),
(17, 'Mei',      'Chen',      'mei.chen@example.net',         'Vancouver',  'CA', '2024-06-16 20:33:00+00'),
(18, 'Lucas',    'Silva',     'lucas.silva@example.com',      'Lisbon',     'PT', '2024-07-01 10:48:00+00'),
(19, 'Grace',    'Walker',    'grace.walker@example.org',     'Glasgow',    'GB', '2024-07-12 12:12:00+00'),
(20, 'Samuel',   'Adeyemi',   'sam.adeyemi@example.com',      'London',     'GB', '2024-07-25 08:05:00+00'),
(21, 'Freya',    'Nielsen',   'freya.nielsen@example.net',    'Copenhagen', 'DK', '2024-08-06 14:39:00+00'),
(22, 'Benjamin', 'Carter',    'ben.carter@example.com',       'Boston',     'US', '2024-08-19 23:15:00+00'),
(23, 'Zara',     'Ahmed',     'zara.ahmed@example.org',       'Leicester',  'GB', '2024-09-02 17:57:00+00'),
(24, 'Henry',    'Dubois',    'henry.dubois@example.com',     'Brussels',   'BE', '2024-09-15 11:28:00+00'),
(25, 'Ava',      'Thompson',  'ava.thompson@example.net',     'Chicago',    'US', '2024-10-01 19:40:00+00'),
(26, 'Mateo',    'García',    'mateo.garcia@example.com',     'Barcelona',  'ES', '2024-10-14 09:02:00+00'),
(27, 'Lily',     'Harper',    'lily.harper@example.org',      'Cardiff',    'GB', '2024-11-03 13:53:00+00'),
(28, 'Jonas',    'Weber',     'jonas.weber@example.com',      'Munich',     'DE', '2024-11-20 16:16:00+00'),
(29, 'Ruby',     'Patel',     'ruby.patel@example.net',       'Nottingham', 'GB', '2025-01-09 10:34:00+00'),
(30, 'Finn',     'Murphy',    'finn.murphy@example.com',      'Galway',     'IE', '2025-02-17 15:07:00+00');

-- -------------------------------------------------------------
-- Orders
-- Customers with no orders: 2, 6, 11, 15, 20, 25
-- -------------------------------------------------------------
INSERT INTO orders (id, customer_id, order_number, order_date, status, total_amount, currency) VALUES
-- Olivia Bennett (2)
( 1,  1, 'ORD-10001', '2024-01-12 10:24:00+00', 'delivered',  48.50, 'GBP'),
( 2,  1, 'ORD-10002', '2025-03-04 18:11:00+00', 'delivered', 112.00, 'GBP'),
-- Priya Raman (4)
( 3,  3, 'ORD-10003', '2024-02-02 12:40:00+00', 'delivered',  23.99, 'GBP'),
( 4,  3, 'ORD-10004', '2024-06-18 09:05:00+00', 'refunded',   75.40, 'GBP'),
( 5,  3, 'ORD-10005', '2025-11-27 20:32:00+00', 'delivered', 189.95, 'GBP'),
( 6,  3, 'ORD-10006', '2026-09-19 14:18:00+00', 'shipped',    64.20, 'GBP'),
-- Daniel Okafor (1)
( 7,  4, 'ORD-10007', '2024-02-14 07:55:00+00', 'delivered',  39.00, 'GBP'),
-- Sophie Laurent (3)
( 8,  5, 'ORD-10008', '2024-02-20 16:47:00+00', 'delivered',  58.75, 'EUR'),
( 9,  5, 'ORD-10009', '2024-09-09 11:13:00+00', 'cancelled', 142.30, 'EUR'),
(10,  5, 'ORD-10010', '2026-04-15 19:29:00+00', 'delivered',  96.10, 'EUR'),
-- Hannah Fischer (2)
(11,  7, 'ORD-10011', '2024-03-15 13:02:00+00', 'delivered', 210.00, 'EUR'),
(12,  7, 'ORD-10012', '2025-07-22 08:44:00+00', 'delivered',  34.50, 'EUR'),
-- James Whitaker (1)
(13,  8, 'ORD-10013', '2026-09-22 21:37:00+00', 'pending',    27.80, 'GBP'),
-- Aisha Mensah (4)
(14,  9, 'ORD-10014', '2024-03-21 10:19:00+00', 'delivered',  65.00, 'EUR'),
(15,  9, 'ORD-10015', '2024-08-30 15:51:00+00', 'delivered',  44.25, 'EUR'),
(16,  9, 'ORD-10016', '2025-02-14 12:08:00+00', 'delivered', 129.99, 'EUR'),
(17,  9, 'ORD-10017', '2026-01-06 17:26:00+00', 'refunded',   18.40, 'EUR'),
-- Liam O'Connor (2)
(18, 10, 'ORD-10018', '2024-04-05 09:33:00+00', 'delivered',  81.60, 'EUR'),
(19, 10, 'ORD-10019', '2025-10-31 22:14:00+00', 'delivered',  52.00, 'EUR'),
-- Noah Kim (3)
(20, 12, 'ORD-10020', '2024-05-02 18:45:00+00', 'delivered', 145.00, 'CAD'),
(21, 12, 'ORD-10021', '2025-05-19 14:57:00+00', 'delivered',  67.35, 'CAD'),
(22, 12, 'ORD-10022', '2026-09-14 16:03:00+00', 'shipped',   230.80, 'CAD'),
-- Chloe Martin (1)
(23, 13, 'ORD-10023', '2024-12-10 11:41:00+00', 'delivered',  99.90, 'EUR'),
-- Ethan Brooks (2)
(24, 14, 'ORD-10024', '2024-05-20 23:08:00+00', 'delivered',  74.99, 'USD'),
(25, 14, 'ORD-10025', '2026-08-28 20:22:00+00', 'delivered', 312.45, 'USD'),
-- Oliver Grant (4)
(26, 16, 'ORD-10026', '2024-06-07 08:16:00+00', 'delivered',  29.95, 'GBP'),
(27, 16, 'ORD-10027', '2024-11-29 19:50:00+00', 'delivered', 158.00, 'GBP'),
(28, 16, 'ORD-10028', '2025-06-12 13:27:00+00', 'cancelled',  42.10, 'GBP'),
(29, 16, 'ORD-10029', '2026-09-23 10:09:00+00', 'pending',    87.60, 'GBP'),
-- Mei Chen (1)
(30, 17, 'ORD-10030', '2025-01-21 21:35:00+00', 'delivered', 119.50, 'CAD'),
-- Lucas Silva (2)
(31, 18, 'ORD-10031', '2024-07-09 12:58:00+00', 'delivered',  36.80, 'EUR'),
(32, 18, 'ORD-10032', '2026-03-03 15:20:00+00', 'delivered', 204.15, 'EUR'),
-- Grace Walker (3)
(33, 19, 'ORD-10033', '2024-07-15 09:47:00+00', 'delivered',  22.50, 'GBP'),
(34, 19, 'ORD-10034', '2025-04-08 17:03:00+00', 'delivered',  61.75, 'GBP'),
(35, 19, 'ORD-10035', '2026-09-17 11:31:00+00', 'shipped',   134.00, 'GBP'),
-- Freya Nielsen (1)
(36, 21, 'ORD-10036', '2024-08-20 14:12:00+00', 'delivered', 745.00, 'DKK'),
-- Benjamin Carter (2)
(37, 22, 'ORD-10037', '2024-09-01 22:49:00+00', 'delivered',  89.00, 'USD'),
(38, 22, 'ORD-10038', '2025-12-15 18:06:00+00', 'delivered', 176.40, 'USD'),
-- Zara Ahmed (4)
(39, 23, 'ORD-10039', '2024-09-04 10:38:00+00', 'delivered',  54.99, 'GBP'),
(40, 23, 'ORD-10040', '2025-01-28 16:24:00+00', 'refunded',   31.20, 'GBP'),
(41, 23, 'ORD-10041', '2025-08-19 20:15:00+00', 'delivered',  97.45, 'GBP'),
(42, 23, 'ORD-10042', '2026-09-21 13:44:00+00', 'paid',      143.60, 'GBP'),
-- Henry Dubois (1)
(43, 24, 'ORD-10043', '2025-02-02 09:21:00+00', 'delivered',  68.30, 'EUR'),
-- Mateo García (3)
(44, 26, 'ORD-10044', '2024-10-20 12:30:00+00', 'delivered', 115.00, 'EUR'),
(45, 26, 'ORD-10045', '2025-09-05 17:52:00+00', 'delivered',  47.90, 'EUR'),
(46, 26, 'ORD-10046', '2026-07-11 11:06:00+00', 'delivered',  82.25, 'EUR'),
-- Lily Harper (2)
(47, 27, 'ORD-10047', '2024-11-25 19:13:00+00', 'delivered',  38.40, 'GBP'),
(48, 27, 'ORD-10048', '2026-09-20 08:59:00+00', 'shipped',    71.00, 'GBP'),
-- Jonas Weber (1)
(49, 28, 'ORD-10049', '2025-03-17 15:36:00+00', 'delivered', 156.70, 'EUR'),
-- Ruby Patel (2)
(50, 29, 'ORD-10050', '2025-01-14 10:27:00+00', 'delivered',  26.99, 'GBP'),
(51, 29, 'ORD-10051', '2026-02-27 21:48:00+00', 'delivered', 109.50, 'GBP'),
-- Finn Murphy (3)
(52, 30, 'ORD-10052', '2025-02-20 13:55:00+00', 'delivered',  44.00, 'EUR'),
(53, 30, 'ORD-10053', '2025-11-11 18:40:00+00', 'cancelled',  92.80, 'EUR'),
(54, 30, 'ORD-10054', '2026-09-18 16:17:00+00', 'shipped',   138.25, 'EUR');

-- Move identity sequences past the explicit IDs so new inserts don't collide
SELECT setval(pg_get_serial_sequence('customers', 'id'), (SELECT MAX(id) FROM customers));
SELECT setval(pg_get_serial_sequence('orders',    'id'), (SELECT MAX(id) FROM orders));

COMMIT;

-- Quick sanity check (optional):
-- SELECT c.id, c.first_name || ' ' || c.last_name AS name, COUNT(o.id) AS orders
-- FROM customers c LEFT JOIN orders o ON o.customer_id = c.id
-- GROUP BY c.id ORDER BY c.id;

BEGIN;

-- Create the roles if they don't already exist, so this can be re-run
DO $$
BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'pgadmin') THEN
        CREATE ROLE pgadmin WITH LOGIN PASSWORD 'pgadmin';
    END IF;
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'limited_user') THEN
        CREATE ROLE limited_user WITH LOGIN PASSWORD 'limited_user';
    END IF;
END $$;

-- pgadmin: full access to everything in the public schema
GRANT ALL PRIVILEGES ON SCHEMA public                 TO pgadmin;
GRANT ALL PRIVILEGES ON ALL TABLES    IN SCHEMA public TO pgadmin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO pgadmin;

-- limited_user: orders table only, no access to customers
REVOKE ALL ON customers FROM limited_user;
GRANT USAGE ON SCHEMA public TO limited_user;
GRANT SELECT, INSERT, UPDATE, DELETE ON orders TO limited_user;
GRANT USAGE ON SEQUENCE orders_id_seq TO limited_user;

COMMIT;
